name: Deploy Laravel App To Live VPS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Staging Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_IP }} << 'EOF'
            cd ${{ secrets.APP_PATH }} # Navigate to the staging folder

            git pull origin main  # Pull the latest changes from main branch
            composer install  # Install dependencies
            
            # php artisan db:seed
            php artisan migrate --force  # Migrate the database
            php artisan optimize:clear  # Clear the optimization
            php artisan cache:clear  # Clear the cache
            php artisan view:clear  # Clear the view cache
            php artisan route:clear  # Clear the route cache
            php artisan optimize  # Optimize the app
            # npm install  # Install dependencies
            # npm run build  # Build the Node app
          EOF
